[package]
name = "wm-backend-headless"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Deterministic headless Horyzond window-system adapter."

[dependencies]
wm-backend = { path = "../wm-backend" }
wm-types = { path = "../wm-types" }

[lints]
workspace = true
